=== rv1971/alcamo-scan/xsd/scan-conf.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema
    xmlns="https://github.com/rv1971/alcamo-scan/conf/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:c="https://github.com/rv1971/alcamo-scan/conf/"
    targetNamespace="https://github.com/rv1971/alcamo-scan/conf/"
    elementFormDefault="qualified"
    dc:title="Scan configuration"
    dc:creator="RV1971 &lt;rv1971@web.de&gt;"
    dc:created="2026-01-05"
    dc:modified="2026-01-10"
    xml:lang="en">
  <xsd:import
      namespace="http://purl.org/dc/terms/"
      schemaLocation="../vendor/alcamo/dom/xsd/dc.xsd"/>

  <xsd:annotation>
    <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
      <h2>Simple types</h2>
    </xsd:documentation>
  </xsd:annotation>

  <xsd:simpleType name="Dates" id="Dates">
    <xsd:list>
      <xsd:simpleType>
        <xsd:restriction base="xsd:date">
          <xsd:pattern value="[12][0-9]{3}-[0-9]{2}-[0-9]{2}"/>
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:list>
  </xsd:simpleType>

  <xsd:simpleType name="Geometry" id="Geometry">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:pattern value="\d+x\d+(\+\d+\+\d+)?"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="Id" id="Id">
    <xsd:restriction base="xsd:NCName"/>
  </xsd:simpleType>

  <xsd:simpleType name="Format" id="Format">
    <xsd:restriction base="Id">
      <xsd:enumeration value="jpeg" id="jpeg"/>
      <xsd:enumeration value="png" id="png"/>
      <xsd:enumeration value="pnm" id="pnm"/>
      <xsd:enumeration value="tiff" id="tiff"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="Mode" id="Mode">
    <xsd:restriction base="Id">
      <xsd:enumeration value="binary" id="binary"/>
      <xsd:enumeration value="color" id="color"/>
      <xsd:enumeration value="gray" id="gray"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="NetDeviceName" id="NetDeviceName">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:pattern value="\c+:net:\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\:\d{1,5}"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="PageNo" id="PageNo">
    <xsd:restriction base="xsd:unsignedShort">
      <xsd:minInclusive value="1"/>
      <xsd:maxInclusive value="9999"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="PageNoIncrement" id="PageNoIncrement">
    <xsd:annotation>
      <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
        <p>The values from -10 to 10 except 0.</p>
      </xsd:documentation>
    </xsd:annotation>

    <xsd:restriction base="xsd:byte">
      <xsd:minInclusive value="-10"/>
      <xsd:maxInclusive value="10"/>
      <xsd:pattern value="-?[^0].*"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="UsbDeviceName" id="UsbDeviceName">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:pattern value="\c+:libusb:\d{1,3}:\d{1,3}"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="UsbId" id="UsbId">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:pattern value="[0-9a-f]{4}:[0-9a-f]{4}"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:annotation>
    <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
      <h2>Settings</h2>
    </xsd:documentation>
  </xsd:annotation>

  <xsd:complexType name="AbstractSettings">
    <xsd:attribute ref="dc:language"/>
    <xsd:attribute ref="dc:type"/>

    <xsd:attribute name="autopdf" type="xsd:boolean" default="false"/>
    <xsd:attribute name="bufferSize" type="xsd:unsignedShort"/>
    <xsd:attribute name="geometry" type="Id"/>
    <xsd:attribute name="mode" type="Mode"/>
    <xsd:attribute name="resolution" type="xsd:unsignedShort"/>
  </xsd:complexType>

  <xsd:complexType name="Settings">
    <xsd:complexContent>
      <xsd:extension base="AbstractSettings">
        <xsd:attribute name="format" type="Format" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="AbstractDevice" abstract="true">
    <xsd:complexContent>
      <xsd:extension base="AbstractSettings">
        <xsd:sequence>
          <xsd:element name="modes" minOccurs="0">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="mode" maxOccurs="unbounded">
                  <xsd:complexType>
                    <xsd:simpleContent>
                      <xsd:extension base="Id">
                        <xsd:attribute name="id" type="Mode" use="required"/>
                      </xsd:extension>
                    </xsd:simpleContent>
                  </xsd:complexType>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>

          <xsd:element name="sources" minOccurs="0">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="source" maxOccurs="unbounded">
                  <xsd:complexType>
                    <xsd:simpleContent>
                      <xsd:extension base="xsd:string">
                        <xsd:attribute name="id" type="Id" use="required"/>
                        <xsd:attribute
                            name="isAdf"
                            type="xsd:boolean"
                            default="false"/>
                      </xsd:extension>
                    </xsd:simpleContent>
                  </xsd:complexType>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>

        <xsd:attribute name="id" type="Id" use="required"/>
        <xsd:attribute name="source" type="Id"/>
        <xsd:attribute
            name="supportsXYResolution"
            type="xsd:boolean"
            default="false"/>

        <xsd:attribute name="format" type="Format"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="NetDevice">
    <xsd:complexContent>
      <xsd:extension base="AbstractDevice">
        <xsd:attribute name="name" type="NetDeviceName" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="UsbDevice">
    <xsd:complexContent>
      <xsd:extension base="AbstractDevice">
        <xsd:attribute name="usbId" type="UsbId" use="required"/>
        <xsd:attribute name="backend" type="xsd:NCName" use="required"/>

        <xsd:attribute name="name" type="UsbDeviceName">
          <xsd:annotation>
            <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
              <p>This is not set in the configuration file but added
              while processing.</p>
            </xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:annotation>
    <xsd:documentation xmlns="http://www.w3.org/1999/xhtml">
      <h2>Document element</h2>
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="conf">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="geometries">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="geometry" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="Geometry">
                      <xsd:attribute name="id" type="Id" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>

          <xsd:unique name="geometry-id">
            <xsd:selector xpath="c:geometry"/>
            <xsd:field xpath="@id"/>
          </xsd:unique>
        </xsd:element>

        <xsd:element name="defaults" type="Settings"/>

        <xsd:element
            name="device"
            type="AbstractDevice"
            minOccurs="0"
            maxOccurs="unbounded">
          <xsd:unique name="mode-id">
            <xsd:selector xpath="c:modes/c:mode"/>
            <xsd:field xpath="@id"/>
          </xsd:unique>

          <xsd:keyref name="mode-ref" refer="mode-id">
            <xsd:selector xpath="."/>
            <xsd:field xpath="@mode"/>
          </xsd:keyref>

          <xsd:unique name="source-id">
            <xsd:selector xpath="c:sources/c:source"/>
            <xsd:field xpath="@id"/>
          </xsd:unique>

          <xsd:keyref name="source-ref" refer="source-id">
            <xsd:selector xpath="."/>
            <xsd:field xpath="@source"/>
          </xsd:keyref>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:unique name="device-id">
      <xsd:selector xpath="c:device"/>
      <xsd:field xpath="@id"/>
    </xsd:unique>

    <xsd:keyref name="defaults-geometry-ref" refer="geometry-id">
      <xsd:selector xpath="c:defaults"/>
      <xsd:field xpath="@geometry"/>
    </xsd:keyref>

    <xsd:keyref name="device-geometry-ref" refer="geometry-id">
      <xsd:selector xpath="c:device"/>
      <xsd:field xpath="@geometry"/>
    </xsd:keyref>
  </xsd:element>
</xsd:schema>

=== rv1971/alcamo-scan/tests/alcamo/conf.xml
<?xml version="1.0"?>

<conf
    xmlns="https://github.com/rv1971/alcamo-scan/conf/"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/rv1971/alcamo-scan/conf/ ../../xsd/scan-conf.xsd"
    dc:created="2026-01-06">
  <pathnames
      exiftool="/usr/bin/exiftool"
      lsusb="/usr/bin/exiftool"
      scanimage="/usr/bin/scanimage"/>

  <geometries>
    <geometry id="a4">210x297</geometry>
    <geometry id="a5">148x210</geometry>
    <geometry id="a5r">210x148</geometry>
    <geometry id="a6">105x148</geometry>
    <geometry id="a6r">148x105</geometry>
    <geometry id="a7">74x105</geometry>
    <geometry id="a7r">105x74</geometry>
  </geometries>

  <defaults
      dc:language="en"
      dc:type="Text"
      autopdf="true"
      bufferSize="64"
      format="jpeg"
      geometry="a4"
      mode="color"
      resolution="150"/>

  <!-- example devices -->

  <device
      xsi:type="NetDevice"
      id="epkowa"
      name="epkowa:net:192.168.178.42:1865"
      source="adf"
      supportsXYResolution="true">
    <modes>
      <mode id="binary" backendId="Binary"/>
      <mode id="color"  backendId="Color"/>
      <mode id="gray"   backendId="Gray"/>
    </modes>

    <sources>
      <source id="adf" backendId="Automatic Document Feeder" isAdf="true"/>
      <source id="flatbed" backendId="Flatbed"/>
    </sources>
  </device>

  <device
      xsi:type="UsbDevice"
      id="fooscan"
      usbId="ffff:0000"
      backend="genesys">
    <modes>
      <mode id="binary" backendId="Lineart"/>
      <mode id="color"  backendId="Color"/>
      <mode id="gray"   backendId="Gray"/>
    </modes>
  </device>
</conf>
